source "https://rubygems.org"

ruby "4.0.0"

gem "rails", "8.1.2"
gem "propshaft", "1.3.1"
gem "sqlite3", "2.9.1", force_ruby_platform: true
gem "puma", "7.2.0"
gem "importmap-rails", "2.2.3"
gem "turbo-rails", "2.0.23"
gem "stimulus-rails", "1.3.4"
gem "jbuilder", "2.14.1"
gem "tzinfo-data", "2.0.6", platforms: %i[ windows jruby ]
gem "solid_cache", "1.0.10"
gem "solid_queue", "1.3.2"
gem "solid_cable", "3.0.12"
gem "bootsnap", "1.23.0", require: false
gem "bigdecimal"

group :development, :test do
  gem "debug", "1.11.1", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "8.0.4"
  gem "capybara", "3.40.0"
  gem "simplecov", "0.22.0", require: false
  gem "bundler-audit", "0.9.3", require: false
  gem "brakeman", "8.0.4", require: false
  gem "rubocop-rails-omakase", "1.1.0", require: false
  gem "reek", "6.5.0", require: false
end

group :development, :desktop do
  gem "web-console", "4.3.0"
  gem "bullet", "8.1.0"
  gem "hotwire-spark", "0.1.13"
end
